"""How much does the LLM add over ``MockCoach``? Answered from stored audits.

`AI_FEEDBACK_IMPROVEMENTS.md` §1.2: the prose is 15 templates and the numbers
are JSON-schema constants, so the model's whole freedom is *which*
``(corner, metric)`` pairs to cite. If it picks what a deterministic ranker
would have picked anyway, "AI coaching" is a claim the paper has to soften.

That is checkable without loading the model. Every audit file already stores
the exact evidence packet the provider was given (``audit.py``), so MockCoach
can be replayed over the same packet and the two selections compared. Nothing
is inferred, nothing is regenerated, no audit is rewritten.

    python scripts/coach_overlap.py [sessions_dir] [--json out.json]

Read-only. ``sessions_dir`` defaults to the workspace's ``sessions/``.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from f1coach_core.coach import MockCoach  # noqa: E402
from f1coach_core.workspace import sessions_root  # noqa: E402

# Generated by scripts/make_sample_session.py, not driven by anybody.
EXCLUDED = {"sample-session"}


def _citations(findings: list[dict]) -> list[tuple[str, str]]:
    """Every ``(corner, metric)`` a report pointed at, in order, deduplicated."""
    seen: set[tuple[str, str]] = set()
    out: list[tuple[str, str]] = []
    for finding in findings:
        for cite in finding["evidence"]:
            key = (cite["corner"], cite["metric"])
            if key not in seen:
                seen.add(key)
                out.append(key)
    return out


def _heads(findings: list[dict]) -> list[tuple[str, str]]:
    """The lead citation of each finding -- what that card is actually about.

    Compared separately from the full citation set because a card is one piece
    of advice: two reports that cite the same corner in passing are not saying
    the same thing if they lead with different metrics.
    """
    return [(f["evidence"][0]["corner"], f["evidence"][0]["metric"]) for f in findings]


def compare(sessions: Path) -> list[dict]:
    rows = []
    for path in sorted(sessions.glob("*/coaching/*.json")):
        session = path.parent.parent.name
        if session in EXCLUDED:
            continue
        audit = json.loads(path.read_text(encoding="utf-8"))
        if not audit.get("ok") or not audit.get("report"):
            continue  # a failed call has no selection to compare

        evidence = audit["evidence_summary"]
        served = audit["report"]["findings"]
        mock = MockCoach().generate(evidence).to_dict()["findings"]

        served_cites, mock_cites = set(_citations(served)), set(_citations(mock))
        served_heads, mock_heads = _heads(served), _heads(mock)
        union = served_cites | mock_cites

        rows.append(
            {
                "session": session,
                "lap": audit["lap"],
                "provider": audit["provider"],
                "written_at": audit["written_at"],
                "mode": evidence.get("analysis_mode"),
                "cards_served": len(served),
                "cards_mock": len(mock),
                "same_cards_same_order": served_heads == mock_heads,
                "head_overlap": len(set(served_heads) & set(mock_heads)),
                "head_union": len(set(served_heads) | set(mock_heads)),
                "citation_jaccard": len(served_cites & mock_cites) / len(union)
                if union
                else 1.0,
                "prose_identical": [
                    (f["issue"], f["cause"], f["action"]) for f in served
                ]
                == [(f["issue"], f["cause"], f["action"]) for f in mock],
                "heads_served": served_heads,
                "heads_mock": mock_heads,
            }
        )
    return rows


def report(rows: list[dict]) -> None:
    if not rows:
        print("no successful audits found")
        return

    sessions = {row["session"] for row in rows}
    print(f"{len(rows)} audits, {len({r['lap'] for r in rows})} laps, "
          f"{len(sessions)} sessions")
    print(f"providers: {dict(Counter(r['provider'] for r in rows))}")
    print(f"written:   {min(r['written_at'] for r in rows)}"
          f" -> {max(r['written_at'] for r in rows)}")
    print()

    hits = sum(row["head_overlap"] for row in rows)
    total = sum(row["head_union"] for row in rows)
    print(f"same cards, same order : {sum(r['same_cards_same_order'] for r in rows)}"
          f"/{len(rows)}")
    print(f"identical prose        : {sum(r['prose_identical'] for r in rows)}"
          f"/{len(rows)}")
    print(f"lead-citation overlap  : {hits}/{total} = {hits / total:.2f}")
    print("mean citation Jaccard  : "
          f"{sum(r['citation_jaccard'] for r in rows) / len(rows):.2f}")

    for mode in sorted({row["mode"] for row in rows}):
        sub = [row for row in rows if row["mode"] == mode]
        served = Counter(metric for row in sub for _, metric in row["heads_served"])
        mock = Counter(metric for row in sub for _, metric in row["heads_mock"])
        print(f"\n=== {mode} ({len(sub)} audits) ===")
        print(f"  lead metric, served : {dict(served.most_common())}")
        print(f"  lead metric, mock   : {dict(mock.most_common())}")
        print("  cards per report    : "
              f"served {dict(sorted(Counter(r['cards_served'] for r in sub).items()))}"
              f"  mock {dict(sorted(Counter(r['cards_mock'] for r in sub).items()))}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("sessions", nargs="?", type=Path)
    parser.add_argument("--json", type=Path, help="write the per-audit rows here")
    args = parser.parse_args(argv)

    sessions = args.sessions or sessions_root()
    if not sessions.is_dir():
        parser.error(f"no sessions directory at {sessions}")

    rows = compare(sessions)
    report(rows)
    if args.json:
        args.json.write_text(json.dumps(rows, indent=2), encoding="utf-8")
        print(f"\nwrote {args.json}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
